name: MMODungeon
version: '${version}'
main: com.binggre.mmodungeon.MMODungeon
api-version: '1.20'
depend: [ 'BinggreAPI', 'MongoLibraryPlugin', 'MMOCore', 'MythicMobs', 'MythicLib' ]
commands:
  인던:
    permission: mmodungeon.admin